### ISSUE TITLE
Sparks won't appear after version 0.10

### ISSUE THREAD

**Issue by hiddenmask58** [xan1242/NFSMW_XenonEffects#2]
Hello I noticed the sparks wont appear since version 0.10

This is the new version 1.00, and I also tested the version 0.11 and 0.12 :

https://user-images.githubusercontent.com/116533167/220818479-3ab36c89-9035-4b0e-9d28-a02f30208054.mp4

And this is version 0.10 :

https://user-images.githubusercontent.com/116533167/220818590-165b79a0-978d-4c2d-952f-95284aa79b9a.mp4

All of the .ini files are kept in vanilla so it's must be not from the settings. I suspect it's been like that since you switched the texture file reading from .dds to .tpk because when I removed the .dds file from version 0.10, the same bug happen. And also because texture file switching was the biggest changelog from version 0.10 to 0.11

**Comment by xan1242** [comment]
Is "Texture Filtering" enabled in Video settings? If not, enable it. (max it out)

Secondly, XenonEffects.tpk must be in the GLOBAL folder.

I've already went through these issues with someone else and fixed it in 0.12

**Comment by xan1242** [comment]
And thirdly, use the latest INI file.

**Comment by hiddenmask58** [comment]
Yes, I already maxed the video settings. The Tpk files is also in global folder and and I already use the latest .ini file

**Comment by xan1242** [comment]
Do the sparks appear after changing video settings? Change any setting, exit out of the menu, and see if they appear.

If so, then it's a bug with the initialization. Possibly a conflict with another mod you might have installed.

If not, then it's a problem with the texture loading and/or a bigger conflict.

In any case, which ASI mods do you also have installed?

**Comment by hiddenmask58** [comment]
![Screenshot (371)](https://user-images.githubusercontent.com/116533167/220821211-d3b84381-c485-4ccb-bf9c-8e9552401967.png)
This is my asi file. I already changed the video settings both in game and in menu and still no changes

**Comment by xan1242** [comment]
I need you to do the following:

- Disable everything except WS fix and Extra Options
- See if sparks work then

If they do, then it's a conflict. In that case, put back ASIs one by one, relaunch the game each time and tell me after which ASI it breaks so I know what's going on.

If they don't, then it's something else. Maybe your exe? I've tested this on a bone-stock game with nothing but ASI loader and it worked fine.

**Comment by hiddenmask58** [comment]
So I've testing for a while and apparently nextgengraphics.asi was the culprit. I tested without it and the sparks appear just fine

**Comment by xan1242** [comment]
Please test the latest release and enable `UseD3DDeviceTexture` in the .ini

https://github.com/xan1242/NFSMW_XenonEffects/releases/download/1.02/NFSMW_XenonEffects.zip

**Comment by hiddenmask58** [comment]
Wow thank you so much! Now the sparks appear normally on the newest version. Appreciate your hardwork so you can close this comment as solved now
