### ISSUE TITLE
speed.exe has stopped working

### ISSUE THREAD

**Issue by BrankoGames44** [xan1242/NFSMW_XenonEffects#4]
Hello! All good? My name is Waldecy and I have a YouTube channel called Banko Games. I'm using "Xenon Effects" in NFSMW 2005 and also the last update of "Extra Options". When I press the "Backspace" key the game stops with the following message box "speed.exe has stopped working". Can you help me?

**Comment by xan1242** [comment]
https://github.com/ExOptsTeam/NFSMWExOpts/releases/tag/v10.0.1.1337

You're not running the latest build, then. Use this build and it'll work.

**Comment by BrankoGames44** [comment]
Thanks.

**Comment by BrankoGames44** [comment]
It worked here. Thanks. Is there a way to return the "ShowMoreCustomizationOptions" function in NFSMWExtraOptionsSettings? I thank.
